SELECT IF(GRADES.Grade >= 8, STUDENTS.Name, NULL), GRADES.Grade, STUDENTS.Marks
FROM GRADES, STUDENTS
WHERE STUDENTS.Marks BETWEEN GRADES.Min_Mark AND GRADES.Max_Mark
ORDER BY GRADES.Grade DESC, STUDENTS.Name;